name: Build and push MapProxy docker image STABLE

on:
  push:
    branches:
      - main
    paths:
      - 'mapproxy/**'
      - '.github/workflows/**'
      - '!seed.sh'
      - '!.github/workflows/*release.yml'
      - '!.github/workflows/*latest.yml'    

env: 
  TAG: stable

jobs:
  build:
    name: Scan, build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@main          
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{ secrets.IMAGE_NAME_MAPPROXY }}:$TAG mapproxy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.IMAGE_NAME_MAPPROXY }}:${{env.TAG}}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'   
      - name: Login to image registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.IMAGE_REGISTRY_URL }}
          username: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
      - name: Push image
        run: |
          docker push ${{ secrets.IMAGE_NAME_MAPPROXY }}:$TAG
      - name: Sign image with a key
        run: |
          IMAGE_SHA=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.IMAGE_NAME_MAPPROXY }}:$TAG)
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY $IMAGE_SHA
        env:
          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}            
